# Получить сообщения чата
query GetChatMessages($chatId: String!) {
  chatMessages(chatId: $chatId) {
    id
    content
    userId
    userName
    chatId
    createdAt
  }
}

# Создать новое сообщение
mutation CreateChatMessage($input: SendMessageInput!) {
  createChatMessage(input: $input) {
    id
    content
    userId
    userName
    chatId
    createdAt
  }
}

# Подписка на новые сообщения
subscription CreatedChatMessage($chatId: String!) {
  createdChatMessage(chatId: $chatId) {
    id
    content
    userId
    userName
    chatId
    createdAt
  }
}
