query GetPlayerResources($playerId: String!) {
  playerResources(playerId: $playerId) {
    playerId
    resources {
      id
      type
      icon
      name
      amount
      updatedAt
    }
    updatedAt
  }
}

mutation UpdateResource($input: UpdateResourceInput!) {
  updateResource(input: $input) {
    playerId
    resourceType
    oldAmount
    newAmount
    updatedAt
  }
}

mutation AddToResource(
  $playerId: String!
  $resourceType: String!
  $amount: Float!
) {
  addToResource(
    playerId: $playerId
    resourceType: $resourceType
    amount: $amount
  ) {
    playerId
    resourceType
    oldAmount
    newAmount
    updatedAt
  }
}

subscription ResourceUpdated($playerId: String!) {
  resourceUpdated(playerId: $playerId) {
    playerId
    resourceType
    oldAmount
    newAmount
    updatedAt
  }
}

subscription PlayerResourcesUpdated($playerId: String!) {
  playerResourcesUpdated(playerId: $playerId) {
    playerId
    resources {
      id
      type
      icon
      name
      amount
      updatedAt
    }
    updatedAt
  }
}
