type Chat {
  id: ID
  messages: [ChatMessage!]
  type: String
}

type ChatMessage {
  author: ChatMessageAuthor
  content: String
  createdAt: DateTime
  id: ID
}

type ChatMessageAuthor {
  id: ID
  name: String
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type MainResources {
  diamond: Int
  food: Int
  fuel: Int
  id: ID
  steel: Int
  wood: Int
}

type Mutation {
  createChatMessage(input: SendMessageInput!): Boolean
}

type Query {
  chatMessages(chatId: String!): [ChatMessage!]
  chats: [Chat!]
  resourcesMain: MainResources
}

input SendMessageInput {
  chatId: String!
  content: String!
}

type Subscription {
  chatCleanup(chatId: String): Boolean
  createdChatMessage(chatId: String): ChatMessage
  resourcesMainChanged: MainResources
}